### ISSUE TITLE
Lodash offers a similar functionality with "deburr"

### ISSUE THREAD

**Issue by catchin** [unlight/clean-up-string#1]
I just wanted to note that [lodash.deburr](https://lodash.com/docs/4.17.4#deburr) offers a similar functionality (without removing whitespace though). Would help to remove some code here (latins.json).

**Comment by unlight** [comment]
Hi, looks like it is not the same
`_.deburr('семки')` =>`'семки'` // but expected 'semki'
`clean-up-string` is more like for creating slug, maybe name is confusing.

**Comment by catchin** [comment]
Ah okay, understood. Thanks!
